// <auto-generated />
using System;
using EntityPosgardo.infraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EntityPosgardo.Migrations
{
    [DbContext(typeof(InfraestructuraDbContext))]
    [Migration("20221003154355_post")]
    partial class post
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EntityPosgardo.modelo.Mensajes", b =>
                {
                    b.Property<int>("MensajeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MensajeId"));

                    b.Property<string>("MensajesXml")
                        .HasColumnType("text");

                    b.Property<int?>("UsuariosId")
                        .HasColumnType("integer");

                    b.Property<bool>("estado")
                        .HasColumnType("boolean");

                    b.HasKey("MensajeId");

                    b.HasIndex("UsuariosId");

                    b.ToTable("Mensaje");
                });

            modelBuilder.Entity("EntityPosgardo.modelo.Roles", b =>
                {
                    b.Property<int>("RolesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RolesId"));

                    b.Property<string>("Cargo")
                        .HasColumnType("text");

                    b.Property<bool>("estado")
                        .HasColumnType("boolean");

                    b.HasKey("RolesId");

                    b.ToTable("Cargo");

                    b.HasData(
                        new
                        {
                            RolesId = 1,
                            Cargo = "admin",
                            estado = false
                        },
                        new
                        {
                            RolesId = 2,
                            Cargo = "Prueba",
                            estado = false
                        },
                        new
                        {
                            RolesId = 3,
                            Cargo = "escritor",
                            estado = false
                        },
                        new
                        {
                            RolesId = 4,
                            Cargo = "lector",
                            estado = false
                        });
                });

            modelBuilder.Entity("EntityPosgardo.modelo.Usuarios", b =>
                {
                    b.Property<int>("UsuariosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuariosId"));

                    b.Property<string>("Detalle")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RolesId")
                        .HasColumnType("integer");

                    b.Property<bool>("estado")
                        .HasColumnType("boolean");

                    b.Property<string>("nombre")
                        .HasColumnType("text");

                    b.HasKey("UsuariosId");

                    b.HasIndex("RolesId");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("EntityPosgardo.modelo.Mensajes", b =>
                {
                    b.HasOne("EntityPosgardo.modelo.Usuarios", "Usuarios")
                        .WithMany("Mensajes")
                        .HasForeignKey("UsuariosId");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("EntityPosgardo.modelo.Usuarios", b =>
                {
                    b.HasOne("EntityPosgardo.modelo.Roles", "Roles")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolesId");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("EntityPosgardo.modelo.Roles", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("EntityPosgardo.modelo.Usuarios", b =>
                {
                    b.Navigation("Mensajes");
                });
#pragma warning restore 612, 618
        }
    }
}
