// <auto-generated />
using System;
using Infrestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrestructura.Migrations
{
    [DbContext(typeof(ChatSQLiteContext))]
    [Migration("20220930033145_sqlMigration")]
    partial class sqlMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Modelo.Mensajes", b =>
                {
                    b.Property<int>("MensajeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MensajeId");

                    b.Property<DateTime>("Fecha");

                    b.Property<string>("Mensaje");

                    b.Property<int?>("UseridIdUserId");

                    b.HasKey("MensajeId");

                    b.HasIndex("UseridIdUserId");

                    b.ToTable("Mensajes");
                });

            modelBuilder.Entity("Modelo.Roles", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RolId");

                    b.Property<string>("Nombre");

                    b.HasKey("RolId");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("Modelo.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UserId");

                    b.Property<int>("Edad");

                    b.Property<bool>("IsActive");

                    b.Property<int?>("MensajesMensajeId");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<int?>("RolId");

                    b.Property<string>("Usuario");

                    b.HasKey("UserId");

                    b.HasIndex("MensajesMensajeId");

                    b.HasIndex("RolId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Modelo.Mensajes", b =>
                {
                    b.HasOne("Modelo.Users", "UseridId")
                        .WithMany()
                        .HasForeignKey("UseridIdUserId");
                });

            modelBuilder.Entity("Modelo.Users", b =>
                {
                    b.HasOne("Modelo.Mensajes")
                        .WithMany("Destinatario")
                        .HasForeignKey("MensajesMensajeId");

                    b.HasOne("Modelo.Roles", "Rol")
                        .WithMany("ListUsers")
                        .HasForeignKey("RolId");
                });
#pragma warning restore 612, 618
        }
    }
}
